Odev_v9/Controllers/KullaniciController.cs
using DataLayer.Model_VM;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Net.Http;
using DataLayer.Model_Parcala;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataLayer.Model_DBContext;
using Microsoft.EntityFrameworkCore;
using DataLayer.Model_Blog;

namespace Odev_v9.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly Blog_DB context;

        public KullaniciController(IHttpClientFactory httpClientFactory,Blog_DB _DB)
        {
            _httpClientFactory = httpClientFactory;
            context = _DB;
        }
        [HttpGet("TakipEdilecekKategori")]
        public IActionResult TakibeTakip() //normalde burda db koymayacaktım. Ama zaman yetmez dedim ve db yi de buraya ekledim . Birde dropbox için çok uğraştım viewde. ama normalde api den çekilebilecek bişi
        {
            List<string> categories = context.kategoris.Select(x => x.Name).ToList();
            ViewBag.Categories = new SelectList(categories, "Name");
            return View();
           
        }

        [HttpPost] //takip kısmı burayı çalıştırıyordu galiba evet öyle olmalı
        public async Task<IActionResult> Ekle(Link link) 
        {
            string token = HttpContext.Session.GetString("Token");
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            string baseUrl = "https://localhost:7052/api/";
            string metot = "Kullanici/kategori-ekle";

            

            
            string url = string.Concat(baseUrl, metot);
            if (token == null)
            {
                ViewBag.Mesaj = "Token yok olm nereye gidiyorsun";
                return View();
            }
            string jsonPayload = Base64UrlHelper.Base64UrlDecode(token.Split('.')[1]); //işte burası token i parçalıyıp işliyor
            var payload = JsonConvert.DeserializeObject<JwtPayload>(jsonPayload);
            string yazarid = (payload.Name); //name'i aldı

            link.sorgu1= yazarid;

            var content = new StringContent(JsonConvert.SerializeObject(link), Encoding.UTF8, "application/json"); //api ye gönderiyor


            try
            {
                HttpResponseMessage response = await client.PostAsync(url, content);

                if (response.IsSuccessStatusCode)
                {
                    string responseContent = await response.Content.ReadAsStringAsync();
                    ViewBag.Mesaj = responseContent; //işlem sonucu
                    return View();
                }
                else
                {
                    // API hatalarını işleme
                    
                    ViewBag.Mesaj = $"{response.StatusCode}";
                    return View();
                }
            }
            catch (HttpRequestException ex)
            {
                // İstek hatalarını işleme
                return StatusCode(StatusCodes.Status500InternalServerError, $"Request error: {ex.Message}");
            }

        }

        [HttpGet] //başlıkları gösteriyor işte 
        public async Task<IActionResult> Baslik()
        {
            string token = HttpContext.Session.GetString("Token");
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            string baseUrl = "https://localhost:7052/api/";
            string metot = "Kullanici/baslik-goster";




            string url = string.Concat(baseUrl, metot);
            if (token == null)
            {
                ViewBag.Mesaj = "Token yok olm nereye gidiyorsun";
                return View("Ekle");
            }
            string jsonPayload = Base64UrlHelper.Base64UrlDecode(token.Split('.')[1]);
            var payload = JsonConvert.DeserializeObject<JwtPayload>(jsonPayload);
            string yazarid = (payload.Name); //name'i aldı

            Sorgu sor = new Sorgu()
            {
                Name = yazarid
            };

            var content = new StringContent(JsonConvert.SerializeObject(sor), Encoding.UTF8, "application/json");


            try
            {
                HttpResponseMessage response = await client.PostAsync(url, content);

                if (response.IsSuccessStatusCode)
                {
                    string responseContent = await response.Content.ReadAsStringAsync();
                    

                    var linkInt2List = JsonConvert.DeserializeObject<List<Link_int2>>(responseContent);


                    return View(linkInt2List);
                }
                else
                {
                    // API hatalarını işleme
                    ViewBag.Mesaj = $"{response.StatusCode}";
                    return View("Ekle");
                   
                }
            }
            catch (HttpRequestException ex)
            {
                // İstek hatalarını işleme
                return StatusCode(StatusCodes.Status500InternalServerError, $"Request error: {ex.Message}");
            }

        }
        [HttpGet]
        public async Task<IActionResult> Icerik(string sorgu) //Burada MVC döndürecek. MVC YOK !!! Artık var ! çalışıyor (galiba). 
        {
            string token = HttpContext.Session.GetString("Token");
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            string baseUrl = "https://localhost:7052/api/";
            string metot = "Kullanici/oku";


            string url = string.Concat(baseUrl, metot);
            if (token == null)
            {
                return BadRequest("Token yok olm nereye gidiyorsun");
            }
            Sorgu gonder = new Sorgu()
            {
                Name = sorgu
            };

            var content = new StringContent(JsonConvert.SerializeObject(gonder), Encoding.UTF8, "application/json");



            try
            {
                HttpResponseMessage response = await client.PostAsync(url, content);

                if (response.IsSuccessStatusCode)
                {
                    string responseContent = await response.Content.ReadAsStringAsync();

                    var linkInt2List = JsonConvert.DeserializeObject<MakaleVM_v2>(responseContent); 

                    var yazar = context.yazars.Find(linkInt2List.YazarId);
                    var kateg = context.kategoris.Find(linkInt2List.KategoriId);

                    MakaleViewModel doncek = new MakaleViewModel
                    {
                        Baslik = linkInt2List.Baslik,
                        Icerik = linkInt2List.Icerik,
                        Cat = kateg.Name,
                        Yaz = yazar.Name
                    };

                    return View(doncek); //Naptık Ettik makalenizi gettik
                }
                else
                {
                    // API hatalarını işleme

                    ViewBag.Mesaj = $"{response.StatusCode}";
                    return View("Ekle");
                   
                }
            }
            catch (HttpRequestException ex)
            {
                // İstek hatalarını işleme
                return StatusCode(StatusCodes.Status500InternalServerError, $"Request error: {ex.Message}");
            }

        }
    }
}

Odev_v9/Controllers/LoginController.cs
using DataLayer.Model_Login;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Text;
using DataLayer.Model_VM;
using DataLayer.Model_Hatalar;
using Azure;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using DataLayer.Model_Parcala;
using DataLayer.Model_Blog;

namespace Odev_v9.Controllers
{
    public class LoginController : Controller //bak şimdi burası önem arz ediyor. Neden mi şundan ötürü "logine" bak burda
    {
        [HttpGet]
        public IActionResult Register()
        {
            return View(); //register viewi 
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel register)
        {
            string baseUrl = "https://localhost:7052/api/";
            string loginMethod = "Login/olustur";

            if (ModelState.IsValid)
            {
                var serializeUser = JsonConvert.SerializeObject(register);

                StringContent stringContent = new StringContent(serializeUser, Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();

                string url = string.Concat(baseUrl, loginMethod);

                var result = client.PostAsync(url, stringContent).Result;

                string json = await result.Content.ReadAsStringAsync();

               
                if (result.Content.Headers.ContentType.MediaType == "application/json")
                {
                    
                    List<JsonHata> requirements = JsonConvert.DeserializeObject<List<JsonHata>>(json);
                    TempData["Requirements"] = JsonConvert.SerializeObject(requirements);

                    return RedirectToAction("DisplayRequirementsL"); //hata liste olursa böyle döncek 
                }
                else
                {
                    TempData["Requirements"] = json;

                    return RedirectToAction("DisplayRequirements"); //tekse böyle sırf bunun için uğraştımdı vaktinde (bi daha olsa bir daha uğraşırım)
                }
            }

            return View();
        }


        [HttpGet]
        public IActionResult Login() //üsttekini aynısı
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            string baseUrl = "https://localhost:7052/api/";
            string loginMethod = "Login/giris";

            if (ModelState.IsValid)
            {
                var serializeUser = JsonConvert.SerializeObject(login);

                StringContent stringContent = new StringContent(serializeUser, Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();

                string url = string.Concat(baseUrl, loginMethod);

                var result = client.PostAsync(url, stringContent).Result;

                string json = await result.Content.ReadAsStringAsync();

                try
                {
                    Token token = JsonConvert.DeserializeObject<Token>(json);
                    
                    if (token != null)
                    {
                        HttpContext.Session.SetString("Token", token.token);
                        string tokken = HttpContext.Session.GetString("Token");
                        string jsonPayload = Base64UrlHelper.Base64UrlDecode(tokken.Split('.')[1]);
                        var payload = JsonConvert.DeserializeObject<JwtPayload>(jsonPayload);
                        string IsYazar = (payload.IsYazar);
                        string IsUser = (payload.IsUser);
                        string IsAdmin = (payload.IsAdmin);
                        if (IsUser == "true") //bunlar da aslında _layout için yapıldı
                        {
                            HttpContext.Session.SetString("User","Okur"); //çok okur
                            if (IsYazar == "true")
                            {
                                HttpContext.Session.SetString("Yazar", "Yazar,Çok yazar"); //Abi 2 milyar 250 milyoncuk - 2500 kilometre yol gittik abi
                                if (IsAdmin == "true") 
                                {
                                    HttpContext.Session.SetString("Admin", "Biz sizi banlatmadık kicklettik"); //Biz terbiyesizlik yapmadığımız halde bizi warrocktrden banlattınız 
                                }
                            }
                        }
                        return RedirectToAction("Success"); // Başarı durumunda yönlendirme
                    }
                }
                catch (JsonException ex)
                {
                    // Token deserialization hatası
                    if (result.Content.Headers.ContentType.MediaType == "application/json")
                    {
                        try
                        {
                            List<JsonHata> requirements = JsonConvert.DeserializeObject<List<JsonHata>>(json);
                            TempData["Requirements"] = JsonConvert.SerializeObject(requirements);
                            return RedirectToAction("DisplayRequirementsL");
                        }
                        catch (JsonException exe)
                        {
                            // JSON deserialization hatası işleme
                            TempData["Error"] = $"JSON deserialization error: {exe.Message}";
                            return RedirectToAction("Error"); // Hata sayfasına yönlendirme
                        }
                    }
                    else
                    {
                        TempData["Requirements"] = json;

                        return RedirectToAction("DisplayRequirements");
                    }
                    
                }

            }

            return View();
        }
        public async Task<IActionResult> Logout() //çıkış tarafı 
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token"); //token sil
            if (HttpContext.Session.GetString("User") != null) //üsttekileri tek tek sil
            {
                HttpContext.Session.Remove("User");

                if (HttpContext.Session.GetString("Yazar") != null)
                {
                    HttpContext.Session.Remove("Yazar");

                    if (HttpContext.Session.GetString("Admin") != null)
                    {
                        HttpContext.Session.Remove("Admin");
                    }
                }
            }
                                    
            return RedirectToAction("Index", "Home");
        }

        public IActionResult DisplayRequirementsL() //buda maksat viewdi
        {
            // TempData'dan veriyi alma
            if (TempData["Requirements"] is string requirementsJson)
            {
                List<JsonHata> requirements = JsonConvert.DeserializeObject<List<JsonHata>>(requirementsJson);
                return View(requirements);
            }

            return View(new List<JsonHata>());
        }
        public IActionResult DisplayRequirements()//buda maksat viewdi
        {
            // TempData'dan veriyi alma
            if (TempData["Requirements"] is string requirementsJson)
            {
                
                ViewBag.ResponseContent = requirementsJson;
                
            }

            return View();
        }
        public IActionResult Error() //buda maksat viewdi
        {
            // Hata sayfasına yönlendirme
            if (TempData["Error"] is string errorMessage)
            {
                ViewBag.ErrorMessage = errorMessage;
            }

            return View();
        }
        public IActionResult Success() //buda maksat viewdi yok galiba bu da varsada vardır doğrudur.
        {
            // Başarı durumunu gösteren bir View
            return View();
        }
    }
}

Odev_v9/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@* bu da usinglerimiz token öbeği için *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Odev_v9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Odev_v9.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Odev_v9</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* buradaki kod sayesinde token i kullanarak görünümleri değiştirebiliriz *@
                        @if (Context.Session.GetString("Token") != null)
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                            @if (Context.Session.GetString("User") != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="TakibeTakip">Kategori Ekle</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="Baslik">Başlıklar</a>
                                </li>
                                @if (Context.Session.GetString("Yazar") != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Yazar" asp-action="Makaleler">Yazılan Makaleler</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Yazar" asp-action="MakaleyiYaz">Makale Yaz</a>
                                    </li>
                                    @if (Context.Session.GetString("Admin") != null)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Durumlar">Durumlar</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="MakaleYaz">Makale Yaz</a>
                                        </li>
                                    }
                                }
                            }
                        }
                        else
                        {
                            <li class="nav-item">

                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">Register</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Odev_v9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>